track_high_thresh:
  type: uniform
  default: 0.6  # from the default parameters
  range: [0.3, 0.7]

track_low_thresh:
  type: uniform
  default: 0.1  # from the default parameters
  range: [0.1, 0.3]

new_track_thresh:
  type: uniform
  default: 0.7  # from the default parameters
  range: [0.1, 0.8]

track_buffer:
  type: randint
  default: 300  # from the default parameters
  range: [20, 81]

match_thresh:
  type: uniform
  default: 0.8  # from the default parameters
  range: [0.1, 0.9]

proximity_thresh:
  type: uniform
  default: 0.4 # from the default parameters
  range: [0.25, 0.75]

appearance_thresh:
  type: uniform
  default: 0.1  # from the default parameters
  range: [0.1, 0.8]

cmc_method:
  type: choice
  default: ecc  # from the default parameters
  options: [sof, ecc]

# --- Birth control parameters ---
birth_roi:
  type: choice
  default: edge
  options: [edge, full]

birth_margin:
  type: uniform
  default: 0.08
  range: [0.02, 0.2]

birth_wait:
  type: randint
  default: 10
  range: [0, 10]